# Generated by Django 4.2.17 on 2025-01-01 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
